### PR TITLE
fix emoji == and Equals

### LINKED ISSUE #966: DiscordEmoji operator == shoulnd't compare names
In https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Entities/Emoji/DiscordEmoji.cs, we have

```csharp
        public static bool operator ==(DiscordEmoji e1, DiscordEmoji e2)
        {
            var o1 = e1 as object;
            var o2 = e2 as object;

            if ((o1 == null && o2 != null) || (o1 != null && o2 == null))
                return false;

            return o1 == null && o2 == null ? true : e1.Id == e2.Id && e1.Name == e2.Name;
        }
```

Note the ` && e1.Name == e2.Name`.

This means that `<:foo:1234>` is not equivalent to `<:bar:1234>`, even though it's a reference to the same emoji. Discord doesn't even care what you put between the colons. Is that intentional?

The following, used in a reaction add/remove event handler, started failing after renaming the emoji in the guild.

```csharp
args.Emoji == guild.Emojis[1234]
```

* `args.Emoji` has whatever name was provided when the reaction was created.
* `guild.Emojis[1234]` has the new name (at least after a restart)

ok, fine, that can be solved using 

```csharp
args.Emoji.Id == guild.Emojis[1234]?.Id
```

But it also prevents putting the emojis in a HashSet, deduplicating a set of emojis, and whatever else uses the standard compare function. 

I posit `operator ==` should ignore differences in names.

### PR DESCRIPTION
**Pull request by IDoEverything**
# Summary
Resolves #966 

# Details
Changes `Equals` and the `==` operator to not check names for non-unicode or guild emojis

### CODE REVIEW

File: DSharpPlus/Entities/Emoji/DiscordEmoji.cs [hunk 1]
```diff
@@ -141,7 +141,7 @@ public bool Equals(DiscordEmoji e)
             if (e is null)
                 return false;
 
-            return ReferenceEquals(this, e) ? true : this.Id == e.Id && this.Name == e.Name;
+            return ReferenceEquals(this, e) || (this.Id == e.Id && (this.Id != 0 || this.Name == e.Name));
```
Comment (VelvetThePanda) [inline DSharpPlus/Entities/Emoji/DiscordEmoji.cs:144]: Couldn't this be simplified to `|| (this.Id == e.Id || this.Name == e.Name)`?

Comment (VelvetThePanda) [reply DSharpPlus/Entities/Emoji/DiscordEmoji.cs:144]: Wait nevermind ignore me

Comment (Lulalaby) [reply DSharpPlus/Entities/Emoji/DiscordEmoji.cs:144]: what about 
```csharp
        public bool Equals(DiscordEmoji e)
        {
            return e is null ? false : ReferenceEquals(this, e) ? true : this.Id == e.Id;
        }
```

and

```csharp
        public static bool operator ==(DiscordEmoji e1, DiscordEmoji e2)
        {
            var o1 = e1 as object;
            var o2 = e2 as object;

            return (o1 == null && o2 != null) || (o1 != null && o2 == null)
                ? false
                : o1 == null && o2 == null ? true : e1.Id == e2.Id;
        }
        ```

Comment (VelvetThePanda) [reply DSharpPlus/Entities/Emoji/DiscordEmoji.cs:144]: The top one is bad because any unicode emoji is equal to any other unicode emoji, since they all have the id of `0`

Comment (VelvetThePanda) [reply DSharpPlus/Entities/Emoji/DiscordEmoji.cs:144]: > ```cs
>            return (o1 == null && o2 != null) || (o1 != null && o2 == null)
>               ? false
>                : o1 == null && o2 == null ? true : e1.Id == e2.Id;
>```

This is a clusterfuck

Comment (Lulalaby) [reply DSharpPlus/Entities/Emoji/DiscordEmoji.cs:144]: > The top one is bad because any unicode emoji is equal to any other unicode emoji, since they all have the id of `0`

Ah okay. Didn't thought about this.

**Review by Neuheit — APPROVED** [review]
