### PR TITLE
Fix #1325 - WebhookBuilder Throws Bad Request

### LINKED ISSUE #1325: Using Mention in the WebHookBuilder throws a bad request
Make sure you familiarize yourself with our contributing guidelines.

# Summary
When using 
interactionEvent.Interaction.CreateResponseAsync(InteractionResponseType.DeferredChannelMessageWithSource)

and then trying to edit via the webookBuilder and adding mentions, I get the error: 
Bad request 400

Inner exception:
"{\r\n  \"allowed_mentions\": {\r\n    \"_errors\": [\r\n      {\r\n        \"code\": \"MODEL_TYPE_CONVERT\",\r\n        \"message\": \"Only dictionaries may be used in a ModelType\"\r\n      }\r\n    ]\r\n  }\r\n}"

# Details
Environment: VS2022
Framework: .NET 4.7.2
DSharpPlus Version: 4.3.0-nightly-01143
OS: Windows 11

- Create a message with a button to interact
- Create a method inteeracting with the button and use:
interactionEvent.Interaction.CreateResponseAsync(InteractionResponseType.DeferredChannelMessageWithSource)
- Then create a WeebHookBuilder and add a RoleMention + some content to respond. 

```
try
{
interactionEvent.Interaction.CreateResponseAsync(InteractionResponseType.DeferredChannelMessageWithSource).Wait();
Thred.Sleep(10000);  //some operation happening

DiscordWebhookBuilder webhook = new DiscordWebhookBuilder();

                            DiscordRole role = interactionEvent.Interaction.Guild.GetRole(YOURROLEID);
                            webhook.AddMention(new RoleMention(role));
                            webhook.WithContent("Hello its me");
                            interactionEvent.Interaction.EditOriginalResponseAsync(webhook).Wait();
}
catch (Exception ex)
{
console.writelIne(ex.toString());
}
```

# Steps to reproduce
1. Click the button you created
2. Wait for the error

### PR DESCRIPTION
**Pull request by waffle-lord**
# Summary
Fixes #1325 by Changing `RestWebhookPayloads.Mentions` to use `DiscordMentions` instead of `IEnumerable<IMention>`

# Details
the api expects `"users":[]`, `"roles":[]`, or `"parse":[]` for the allowed_mentions field. The DiscordJson serializer is populating this field with `"id": 123456...` instead which is causing an exception when sending the request. This inadvertently keeps the interaction that created the request alive, seemingly forever.

# Notes
I haven't tested this to any real extent and know very little of this lib... so you know... *shrug

### CODE REVIEW

File: DSharpPlus/Net/Rest/DiscordApiClient.cs [hunk 1]
```diff
@@ -2873,7 +2873,7 @@ internal async Task<DiscordMessage> EditWebhookMessageAsync(ulong webhook_id, st
             {
                 Content = builder.Content,
                 Embeds = builder.Embeds,
-                Mentions = builder.Mentions,
+                Mentions = new DiscordMentions(builder.Mentions ?? Mentions.All, builder.Mentions?.Any() ?? false),
```
Comment (DPlayer234) [inline DSharpPlus/Net/Rest/DiscordApiClient.cs:2876]: `Mentions` should still be `null` if the builder's `Mentions` are `null`.
Not only would this otherwise be inconsistent with previous behavior, but editing a webhook without specifying mentions on the builder would now set it to have everyone in the message mentioned.
(Note the `NullValueHandling` on the payload property.)

Comment (VelvetThePanda) [reply DSharpPlus/Net/Rest/DiscordApiClient.cs:2876]: Truly a flashback of #1054.

File: DSharpPlus/Net/Rest/DiscordApiClient.cs [hunk 2]
```diff
@@ -2869,11 +2869,13 @@ internal async Task<DiscordMessage> EditWebhookMessageAsync(ulong webhook_id, st
         {
             builder.Validate(true);
 
+            var mentions = builder.Mentions != null ? new DiscordMentions(builder.Mentions, builder.Mentions?.Any() ?? false) : null;
```
Comment (DPlayer234) [inline DSharpPlus/Net/Rest/DiscordApiClient.cs:2872]: `builder.Mentions?.Any() ?? false` should just be `builder.Mentions.Any()` since null is already checked, though it shouldn't have a functional impact.
Otherwise, LGTM.

**Review by DPlayer234 — APPROVED** [review]
Looks good to me.

**Comment by OoLunar** [comment]
Tested?

**Comment by waffle-lord** [comment]
I've only tested it with `InteractionContext.EditResponseAsync`, since it uses the webhook builder.

I'm not familiar with how I go about proving this... here's a picture?

image

My garbage test code if you want it
```cs
public class SlashMentionTest : ApplicationCommandModule
    {
        [SlashCommand("mention_test", "Test the webhookbuilder mentions")]
        public async Task MentionTestAsync(InteractionContext context, [Option("Array", "Use mention array option")] bool array = false)
        {
            // your own role ID here
            DiscordRole testRole = context.Guild.GetRole(1004897882253570158);

            var mentions = new IMention[] { new UserMention(context.User), new UserMention(context.Client.CurrentUser), new RoleMention(testRole) };

            // how do you get a mention back from IMention anyway? wish I knew right now ...
            string message = array ? $"Hi {context.User.Mention} {context.Client.CurrentUser.Mention} {testRole.Mention}" : $"Hi {context.User.Mention}";

            await context.CreateResponseAsync(InteractionResponseType.DeferredChannelMessageWithSource);

            // doin stuff
            Thread.Sleep(2000);

            var webhookBuilder = new DiscordWebhookBuilder().WithContent(message);

            if(array)
            {
                // use mentions array
                webhookBuilder.AddMentions(mentions);
            }
            else
            {
                // use single mention
                webhookBuilder.AddMention(new UserMention(context.User));
            }

            await context.EditResponseAsync(webhookBuilder);
        }
    }
```

**Comment by OoLunar** [comment]
Yeah that works. Thanks for your contributions!
