### PR TITLE
Fix Reconnect Bug when Disallowed/Malformed Intents are provided

### LINKED ISSUE #682: [bug] AutoReconnect keeps retrying with disallowed intents
# Summary
The AutoReconnect will keep trying to connect when the bot is being disconnected by Discord because of disallowed intents. The bot shouldn't try to reconnect but instead tell the user (via the logger?) that they are trying to connect with intents they are not whitelisted to use.

# Details
Summary should explain it all. Here a screenshot of what happens:
big oof bub

# Steps to reproduce
1. Disable all intents on bot page on Discord Developers.
2. Connect with `DiscordIntents.All` and `AutoReconnect = true`
3. Loop

# Notes
nah fam issa bug

### PR DESCRIPTION
**Pull request by jeffreyladd**
# Summary
Fixes #682

# Details
Changes the Reconnect logic in SocketOnDisconnect to check the Close code.  If it is due to disallowed Intents or invalid ones, we will not reconnect.  Granted we should never hit a 4013 but placing it there as a saftey measure.

### CODE REVIEW

File: DSharpPlus/Clients/DiscordClient.WebSocket.cs [hunk 1]
```diff
@@ -183,6 +185,10 @@ async Task SocketOnDisconnect(IWebSocketClient sender, SocketCloseEventArgs e)
                     else
                         await this.ConnectAsync(this._status._activity, this._status.Status).ConfigureAwait(false);
                 }
+                else if(e.CloseCode != 4014 || e.CloseCode != 4013)
```
Comment (Neuheit) [inline DSharpPlus/Clients/DiscordClient.WebSocket.cs:188]: This won't log the connection being terminated with these error messages.

**Review by Neuheit — CHANGES_REQUESTED** [review]

**Review by Neuheit — APPROVED** [review]

File: DSharpPlus/Clients/DiscordClient.WebSocket.cs [hunk 2]
```diff
@@ -171,7 +171,9 @@ async Task SocketOnDisconnect(IWebSocketClient sender, SocketCloseEventArgs e)
                 this.Logger.LogDebug(LoggerEvents.ConnectionClose, "Connection closed ({0}, '{1}')", e.CloseCode, e.CloseMessage);
                 await this._socketClosed.InvokeAsync(this, e).ConfigureAwait(false);
 
-                if (this.Configuration.AutoReconnect)
+
+                //CloseCode 4014 is disallowed Intent and CloseCode 4013 is invalid Intent.  We Should not continuously reconnect per issue 682
+                if (this.Configuration.AutoReconnect && e.CloseCode != 4014 && e.CloseCode != 4013)
```
Comment (Emzi0767) [inline DSharpPlus/Clients/DiscordClient.WebSocket.cs:176]: Should not reconnect on any 4xxx other than 4000 since we use that one for """clean""" close.

**Review by Emzi0767 — CHANGES_REQUESTED** [review]

File: DSharpPlus/Clients/DiscordClient.WebSocket.cs (hunk 2 above)
Comment (jeffreyladd) [reply DSharpPlus/Clients/DiscordClient.WebSocket.cs]: Change applied

**Review by Emzi0767 — APPROVED** [review]
