### PR TITLE
Fix for NullReference if no connection was established #554

### LINKED ISSUE #554: DiscordClient::Dispose() throws NullReferenceException if no succesfull connection was established
# Summary
A `NullReferenceException` is thrown when a DiscordClient is destroyed before a succesfull conncection was established. The cause is _webSocketClient being dereferenced without checking whether it is null.

# Steps to reproduce
1. Run the following code:
```
// No, do not change the token. It's invalid on purpose.
DiscordClient? client = new DiscordClient(new DiscordConfiguration{Token = "NotValid"});
try {
    await client.ConnectAsync();
} catch (Exception) {}
client.Dispose();
client = null;
```

# Details
Error was enountered in the v4.0 nightly build NuGet packages (683) and the bug has been verified against the current source on Github.

# Notes
Use of the C# 8.0 nullable feature might help in finding similar errors.

### PR DESCRIPTION
**Pull request by PeskyTheBear**
# Summary
Fixes #554 
Added a null check when disposing the WebsSocketClient and removed the Disconnect because this is done in a nullsafe way in DiscordClient::DisconnectAsync().

# Notes
I picked up this issue because i am relatively new to open source development and this issue looked relatively easy. I would love any feedback😄.

### CODE REVIEW

**Comment by PeskyTheBear** [comment]
I picked up this issue because i am relatively new to open source development and this issue looked relatively easy. I would love any feedback😄.

File: DSharpPlus/DiscordClient.cs [hunk 1]
```diff
@@ -2634,8 +2634,7 @@ public override void Dispose()
             this._guilds = null;
             this._heartbeatTask = null;
             this._privateChannels = null;
-            this._webSocketClient.DisconnectAsync().ConfigureAwait(false).GetAwaiter().GetResult();
```
Comment (Emzi0767) [inline DSharpPlus/DiscordClient.cs:2637]: Not necessary to remove the line, simply wrap both of them into a null check.

Comment (PeskyTheBear) [reply DSharpPlus/DiscordClient.cs:2637]: I removed this because the disconnect call is completely redundant (it is done in both the disconnect of the DiscordClient and the dispose of the WebSocketClient) and there is no check that stops the disconnect if it has been executed previously.
The use of the ? was done because the same was done for the cancelTokenSource ~10 lines above this change.
If it is really preferred I'll add the line back and wrap it in an if statement😃.

**Comment by Emzi0767** [comment]
Sounds like a reasonable explanation. I'll most likely merge once I finish what I'm doing at the moment, so in a couple hours, so I can have a proper look.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
