### PR TITLE
Fix NRE on Serialization of DiscordWebhooks

### LINKED ISSUE #1589: GetWebhooksAsync NRE
# Summary
When you try do get all webhooks you get a NRE

# Details

Versions: 
- Nightly: 5.0.0-nightly-01621
- Stable: 4.4.2

```
   at DSharpPlus.Net.Serialization.DiscordForumChannelJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at DSharpPlus.Net.DiscordApiClient.GetGuildWebhooksAsync(UInt64 guild_id)
   at MADS.Commands.Text.Base.ExitGuild.Test(CommandContext ctx) in /Users/USR/RiderProjects/Mads/ModularAssistentForDiscordServer/Commands/Text/Base/ExitGuild.cs:line 42
```

# Steps to reproduce
1. Try `DiscordGuild#GetWebhooksAsync`

### PR DESCRIPTION
**Pull request by Plerx2493**
# Summary
Add a partial DiscordChannel, change type in DiscordWebhook and add a check in the DiscordForumChannelJsonConverter to get early reports if we handle partial channel objects wrong

Fixes #1589 

# Notes
A draft of changes discussed [here](https://discord.com/channels/379378609942560770/379386901725052928/1129207512697143366)

### CODE REVIEW

File: DSharpPlus/Net/Serialization/DiscordForumChannelJsonConverter.cs [hunk 1]
```diff
@@ -22,56 +22,63 @@
...
+        bool hasType = job.TryGetValue("type", out typeToken);
 
-            if (channelType is ChannelType.GuildForum)
-            {
-                // Type erasure is almost unheard of in C#, but you never know...
-                var chn = new DiscordForumChannel();
-                serializer.Populate(job.CreateReader(), chn);
+        if (!hasType)
+        {
+            throw new SerializationException("Channel object lacks type - this should be reported to library developers");
```
Comment (akiraveliara) [inline DSharpPlus/Net/Serialization/DiscordForumChannelJsonConverter.cs:47]: not convinced of the SerializationException here, particularly because it belongs to S.R.Serialization, which should... generally be avoided. how about Newtonsoft.Json.JsonException instead?

**Review by akiraveliara — APPROVED** [review]
i'm not fully convinced of the documentation comments yet, but that's not the end of all things

File: DSharpPlus/Net/Serialization/DiscordForumChannelJsonConverter.cs (hunk 1 above)
Comment (Plerx2493) [reply DSharpPlus/Net/Serialization/DiscordForumChannelJsonConverter.cs:47]: Sounds good, i only searched for "Serialization"

**Comment by Plerx2493** [comment]
> i'm not fully convinced of the documentation comments yet, but that's not the end of all things

If you have examples i can think about different once

**Comment by Plerx2493** [comment]
btw those are mostly the comments from `DiscordGuild`

**Comment by akiraveliara** [comment]
some comments are grammatically incomplete, crude or not whole sentences as the .NET code design guidelines suggest; but it's fine - if you want to change it here, that's great, if not, that doesn't block merging imo

**Review by akiraveliara — APPROVED** [review]

**Comment by Plerx2493** [comment]
yeah, currently not in the mood to fix it
