### PR TITLE
Union Message Parsed Mentions with Discord Mention Lists

### LINKED ISSUE #782: MentionedUsers does not include the person pinged during a reply.
# Summary
MentionedUsers does not include the person pinged during a reply.

# Details
Ok, so the problem that I found is related to the way that we handle UserMentions and honestly all the other mentions as well. It would appear that we manually parse them out ourselves instead of using the mentioned channels/users/roles that are sent by Discord. Thing is that whether the reply that we were sent pinged the user that it was replying to is in the mentions provided by Discord and not in the mentions that we can parse from the content. My question is why do we manually parse it when Discord hands us the mentions and if it's for an important reason how would you suggest we handle getting the reply mentioned user into the MentionedUsers list. If we can just get rid of the extra parsing I would do so. If we can't then I would suggest combining the list provided by Discord and the list we generate to ensure we aren't accidentally removing information. 

# Steps to reproduce
1. Reply to a message pinging the user in that message with just some string content, no mentions or anything.
2. View the MessageCreatedEventArgs and the Message in those args and you will notice that the MentionedUsers do not include the pinged user even though they should.

### PR DESCRIPTION
**Pull request by ProfDoof**
# Summary
Fixes #782 

# Details
This fixes #782 which prevents the reply mentioned user from showing up in the DSharpPlus MentionedUsers list by unioning the Discord provided Mention lists with the parsed mention lists. The reason that it was decided to union instead of only use the Discord provided lists is that users who are in the cache and are mentioned in a context outside of a guild where they are member are not sent by Discord. So, to circumvent that we parse the message mentions. To ensure that no changes occur for the other mention lists we also union them with whatever is parsed from the message. This allows us to respect old behavior while still ensuring that any Discord-provided data is used. 

One change was made that can easily be remedied, I set all Mention lists to empty lists rather than null. This is because the two separate behaviors didn't really make sense. Especially since Discord always sends the mentioned roles list (even if they don't always send the mention channels list) even if it's empty. So, for consistency's sake, it makes sense to just go ahead and provide empty lists instead. If y'all disagree just comment and let me know and I will change it. 

Also, I need to fix this, I forgot to set the MinimumLogLevel in the TestBot back to Debug. 😆 

# Changes proposed
* Added 4 test commands to test different aspects of the mention parsing and mention objects received from Discord
* Update the User Cache with the partial user objects received from Discord in the mention but only for users that are in some guild and not those that are in DMs. 
* Added a DiscordUserComparer so that I could use a HashSet for unioning the parsed mentions and the discord sent mentioned users together.

### CODE REVIEW

File: DSharpPlus/Net/DiscordApiClient.cs [hunk 1]
```diff
@@ -93,27 +93,38 @@ private void PopulateMessage(TransportUser author, DiscordMessage ret)
...
-                    mentioned_users = Utilities.GetUserMentions(ret).Select(this.Discord.GetCachedOrEmptyUserInternal).ToList();
+                    ret._mentionedRoles = ret._mentionedRoles.Union(Utilities.GetRoleMentions(ret).Select(xid => guild.GetRole(xid))).ToList();
+                    ret._mentionedChannels = ret._mentionedChannels.Union(Utilities.GetChannelMentions(ret).Select(xid => guild.GetChannel(xid))).ToList();
                 }
             }
 
-            ret._mentionedUsers = mentioned_users;
-            ret._mentionedRoles = mentioned_roles;
-            ret._mentionedChannels = mentioned_channels;
+            ret._mentionedUsers = mentionedUsers.ToList();
```
Comment (ProfDoof) [inline DSharpPlus/Net/DiscordApiClient.cs:127]: Yep, here's the duplication. I'll fix this here in a bit.

File: DSharpPlus.Test/TestBot.cs [hunk 2]
```diff
@@ -42,7 +42,7 @@ public TestBot(TestBotConfig cfg, int shardid)
             {
                 AutoReconnect = true,
                 LargeThreshold = 250,
-                MinimumLogLevel = LogLevel.Debug,
+                MinimumLogLevel = LogLevel.Trace,
```
Comment (ProfDoof) [inline DSharpPlus.Test/TestBot.cs:45]:
```suggestion
                MinimumLogLevel = LogLevel.Debug,
```

File: DSharpPlus/Net/DiscordApiClient.cs (hunk 1 above)
Comment (ProfDoof) [reply DSharpPlus/Net/DiscordApiClient.cs]: It's been moved

**Review by Neuheit — APPROVED** [review]

File: DSharpPlus/Clients/DiscordClient.cs [hunk 3]
```diff
@@ -810,28 +810,40 @@ private void PopulateMessageReactionsAndCache(DiscordMessage message, TransportU
...
-        private void PopulateMessageMentions(DiscordMessage message, DiscordGuild guild)
+        private void PopulateMentions(DiscordMessage message, DiscordGuild guild)
         {
-            var mentionedUsers = new List<DiscordUser>();
-            var mentionedRoles = guild != null ? new List<DiscordRole>() : null;
-            var mentionedChannels = guild != null ? new List<DiscordChannel>() : null;
-            if (!string.IsNullOrWhiteSpace(message.Content))
+            message._mentionedUsers ??= new List<DiscordUser>();
+            message._mentionedRoles ??= new List<DiscordRole>();
+            message._mentionedChannels ??= new List<DiscordChannel>();
```
[the remark this answers is not in the document]
Comment (Neuheit) [reply DSharpPlus/Clients/DiscordClient.cs]: Yes thank you for doing that, we need to go through the lib at some point to make sure we aren't returning null collections to the user.
