### PR TITLE
Fixes NRE when request size is too large.

### LINKED ISSUE #417: DiscordApiClient.PrepareMessage() throws NRE
Make sure you familiarize yourself with our contributing guidelines.

# Summary
`NullReferenceException` occurs when trying to upload a file with size greater than the allowed maximum. 

# Details
```
Stack trace:
   at DSharpPlus.Net.DiscordApiClient.PrepareMessage(JToken msg_raw)
   at DSharpPlus.Net.DiscordApiClient.UploadFileAsync(UInt64 channel_id, Stream file_data, String file_name, String content, Nullable`1 tts, DiscordEmbed embed)
```
The lib version is the latest nightly and the bot is running on .NET Core 2.1.

# Steps to reproduce
1. Try to upload a large file (I tried >50MB one) via CommandContext.RespondWithFileAsync()
2. NRE

# Notes
I have searched the code and I haven't found any checks on the Stream passed to DiscordApiClient.UploadFileAsync method. So I assume that the request returned contains `null` response string and that gets passed to DiscordApiClient.PrepareMessage() method, which then throws.

### PR DESCRIPTION
**Pull request by Neuheit**
# Summary
This PR mainly fixes #417, but also adds an initial check and makes a few documentation/output changes.

# Details
If a user tries to upload a file that is greater than the limit, Discord will return code 413: "Request entity too large". Previously, the lib does not handle this, and instead assumes the request succeeded and tries to parse the first property of the message class, which throws the NRE. 

This PR adds this code to the exception list, and throws a custom exception that states the user's request size was too large.

Additionally, I removed a few checks in DiscordChannel.RespondAsync() as the same checks are in DiscordApiClient.CreateMessageAsync(), I added a check when sending multiple files to ensure the user does not send more than 10, and I also added punctuation on a few error messages.

# Changes proposed
* Created a new exception, which properly throws when a request size becomes too large.
* Added/deleted a few checks in various methods for simplicity, and added a check for file count.
* Added punctuation at the end of a few error messages.

### CODE REVIEW

File: DSharpPlus/Exceptions/RequestSizeException.cs [hunk 1]
```diff
@@ -0,0 +1,42 @@
+﻿using System;
+using Newtonsoft.Json.Linq;
+using DSharpPlus.Net;
+
+namespace DSharpPlus.Exceptions
+{
+    /// <summary>
+    /// Represents an exception thrown when the request sent to Discord is too large.
+    /// </summary>
+    class RequestSizeException : Exception
```
Comment (Emzi0767) [inline DSharpPlus/Exceptions/RequestSizeException.cs]: I believe this class should be made public.

Comment (Neuheit) [reply DSharpPlus/Exceptions/RequestSizeException.cs]: Oh whoops, I thought it already was.
