### PR TITLE
Fixes Exceptions Received in VoiceNext Voice Receive

### LINKED ISSUE #493: Exception occurred when decoding incoming audio data
# Summary
An exception occurs when DSharpPlus runs my `VoiceReceived` event handler. The error is along the lines of:

`The given keys cannot be found in the dictionary at DSharpPlus.VoiceNext.VoiceNextConnection.ProcessVoicePacket(Byte[] data)`

# Details
I'm using the latest nightly build of DSharpPlus

Console output:
```
[2019-11-30 11:31:37 +13:00] [VNext RX] [Error] Exception occured when decoding incoming audio data
System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at DSharpPlus.VoiceNext.VoiceNextConnection.ProcessPacket(ReadOnlySpan`1 data, Memory`1& opus, Memory`1& pcm, IList`1 pcmPackets, AudioSender& voiceSender, AudioFormat& outputFormat)
   at DSharpPlus.VoiceNext.VoiceNextConnection.ProcessVoicePacket(Byte[] data)

Event fired.

[2019-11-30 11:31:37 +13:00] [DSharpPlus] [Error] An System.AggregateException occurred in VNEXT_VOICE_RECEIVED.
System.AggregateException: Exceptions occured within one or more event handlers. Check InnerExceptions for details. (The given key '402299820825509899' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key '402299820825509899' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at maxymooapp_DSharp.Program.HandleVoiceData(VoiceReceiveEventArgs voiceData) in C:\Users\Max\Documents\stuff of max\node.js stuff\maxymooapp-DSharp\Program.cs:line 232
   at DSharpPlus.AsyncEvent`1.InvokeAsync(T e)
   --- End of inner exception stack trace ---
```

The code I am using for the event handler:
```
static async Task HandleVoiceData(DSharpPlus.VoiceNext.EventArgs.VoiceReceiveEventArgs voiceData)
{
    if (voiceData.User.IsBot) return;
    Console.WriteLine("Event fired.");
    
    var stereoBufferArray = voiceData.PcmData.ToArray();
    foreach(byte b in stereoBufferArray)
    {
        bufs.Add(b);
    }
}
```
Where bufs is a: `List<byte>`

There is no other code in the event handler so far as I cannot get this part to work.

# Notes
Every once in a while, no exception will be thrown. This usually happens when I don't have `var stereoBufferArray = voiceData.PcmData.ToArray();`  or the `foreach` loop in the code.

Also, in the second part of the error it cant find the key `402299820825509899` in a dictionary. I then realized that `402299820825509899` is my discord user id`

### PR DESCRIPTION
**Pull request by Neuheit**
# Summary
Fixes #493.

# Details
The exception was thrown due to a race condition between the UDP client and Voice WS, in that the UDP was trying to access the SSRC cache before it had the correct SSRC, which is only added by the WS. This PR fixes that by creating a new audio sender with a null user, as there cannot be anything blocking to request the user or wait for the correct SSRC.

# Changes proposed
* Fix key not found exception by creating a new AudioSender with a null user.

# Notes
I don't believe this fixed the user cache exception as well, as that is a much larger issue out of the scope of this PR.

### CODE REVIEW

File: DSharpPlus.VoiceNext/EventArgs/VoiceReceiveEventArgs.cs [hunk 1]
```diff
@@ -14,10 +14,14 @@ public class VoiceReceiveEventArgs : DiscordEventArgs
         /// </summary>
         public uint SSRC { get; internal set; }
 
+        #nullable enable
```
Comment (Emzi0767) [inline DSharpPlus.VoiceNext/EventArgs/VoiceReceiveEventArgs.cs:17]: Ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh. I very much dislike the nullability feature because all it does is cause compiler noise, without really assisting the user. Not that most people read those, but xmldoc note might be far less annoying.

File: DSharpPlus.VoiceNext/VoiceNextConnection.cs [hunk 2]
```diff
@@ -419,7 +419,17 @@ private bool ProcessPacket(ReadOnlySpan<byte> data, ref Memory<byte> opus, ref M
 
             this.Rtp.DecodeHeader(data, out var sequence, out var timestamp, out var ssrc, out var hasExtension);
 
-            var vtx = this.TransmittingSSRCs[ssrc];
+            if(!this.TransmittingSSRCs.TryGetValue(ssrc, out var vtx))
```
Comment (Emzi0767) [inline DSharpPlus.VoiceNext/VoiceNextConnection.cs:422]: space after if

**Review by Emzi0767 — CHANGES_REQUESTED** [review]

**Comment by Emzi0767** [comment]
Eh, I'll take it.
